title: Blog Bibliotheks- und Archivinformatik
author: Felicia
email: felicia.perrucci@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2024

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
